name: ARAddon
main: com.blxxdx.araddon.ARM
version: 1
api-version: 1.16
softdepend:
  - "Essentials"
  - "PlaceholderAPI"
commands:
  araddon:
    permission: araddon.op
permissions:
  araddon.op:
    default: op